AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Restana Serverless

  Sample application that shows how to run restana applications as lambdas
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: restana-service-01/
      Handler: lambda.handler
      Runtime: nodejs12.x
      Events:
        Http:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Http:
    Description: "API Gateway endpoint URL for Prod stage for Service function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hi"
  ServiceFunction:
    Description: "Service Lambda Function ARN"
    Value: !GetAtt ServiceFunction.Arn
  ServiceFunctionIamRole:
    Description: "Implicit IAM Role created for Service function"
    Value: !GetAtt ServiceFunctionRole.Arn
